---
# tasks file for timezone (Ubuntu specific)

- name: Create timezone file
  become: yes
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify:
    - update tzdata
  when: ansible_distribution_release == "trusty"
  tags:
    - timezone

- name: Create timezone file
  become: yes
  file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone_name }}
    force: yes
    owner: root
    group: root
    state: link
  notify:
    - update tzdata
  when: ansible_distribution_release == "xenial"
  tags:
    - timezone
